### ISSUE TITLE
Implement Activity Events

### ISSUE THREAD

**Issue by habanoz** [habanoz/flutter-mapbox-sdk10#2]
Crash with following stack trace.

D/AndroidRuntime( 6919): Shutting down VM,
E/AndroidRuntime( 6919): FATAL EXCEPTION: main
E/AndroidRuntime( 6919): Process: com.habanoz.mapbox.maps10_example, PID: 6919
E/AndroidRuntime( 6919): kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
E/AndroidRuntime( 6919):        at com.habanoz.mapbox.maps10.Maps10Plugin.onDetachedFromActivity(Maps10Plugin.kt:61)
E/AndroidRuntime( 6919):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:383)
E/AndroidRuntime( 6919):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:681)
E/AndroidRuntime( 6919):        at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:715)
E/AndroidRuntime( 6919):        at android.app.Activity.performDestroy(Activity.java:8542)

**Comment by habanoz** [comment]
#3 solves.
